snprintf = 0x1e23f0;
malloc = 0x156ea;
free = 0xd12a;
isspace = 0xb040e0;
set_errno = 0xb056a4;
get_errno = 0xb05610;
strtol = 0x4516;
strncpy = 0xae9c20;

SDL_ShowSimpleMessageBox = 0x897f10;
cJSON_GetObjectItemCaseSensitive = 0x187a;
cJSON_IsObject = 0x1d51b;

_ZN15FileSystemUtils9CreateDirEPKc = 0x460550;
_ZN11Environment8instanceEv = 0x418440;
BallTemplateInfo_initialize = 0x21cd50;
GetImageIdInfo = 0x21d810;
GetGooBallName = 0x279c00;
AddGooballButton = 0x23b380;
/* BallFactory::instance() */
_ZN11BallFactory8instanceEv = 0x20ecf0;

gooballIds = 0x12e6de0;
empty_string = 0xe8194e;

ball_deserialize_hook2_return_error = 0x2162a2;
